# Generated by Django 3.2.18 on 2024-04-13 14:46

import apps.editor.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issn', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Interpreter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('ref_tm', models.CharField(max_length=25, null=True)),
                ('ean', models.CharField(error_messages={'unique': 'Ce code EAN est déjà utilisé par un autre produit.'}, max_length=255, null=True, validators=[apps.editor.validators.ean13_validator])),
                ('title', models.CharField(max_length=255, null=True)),
                ('sub_title', models.CharField(max_length=255, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('number_in_collection', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('circulation', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('publication', models.DateField(null=True)),
                ('width', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_pages', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('presentation_product', models.TextField(null=True)),
                ('presentation_author', models.TextField(null=True)),
                ('strong_points', models.TextField(null=True)),
                ('target_audience', models.TextField(null=True)),
                ('coefficient', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pght', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('recto_img', models.CharField(max_length=255, null=True)),
                ('verso_img', models.CharField(max_length=255, null=True)),
                ('remarques', models.TextField(null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.collection')),
                ('interpreter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.interpreter')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.product')),
            ],
        ),
    ]
