# Generated by Django 4.2 on 2024-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monk',
            name='civil_first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monk',
            name='civil_last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
