# Generated by Django 3.2.25 on 2025-03-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moines', '0002_monk_civil_first_name_monk_civil_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monk',
            name='civil_first_name',
        ),
        migrations.RemoveField(
            model_name='monk',
            name='civil_last_name',
        ),
    ]
