# Generated by Django 3.2.18 on 2024-04-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('moine_flav', models.BooleanField(default=False)),
                ('est_pere_suiveur', models.BooleanField(default=False)),
                ('qualite', models.CharField(max_length=25)),
                ('pretre', models.BooleanField(default=False)),
                ('messe_forme', models.CharField(blank=True, max_length=25, null=True)),
                ('messe_langue', models.CharField(blank=True, max_length=25, null=True)),
                ('commentaire', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('pere_suiveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotellerie.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Retreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tel', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tel_personne', to='hotellerie.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sejour_du', models.DateField()),
                ('sejour_au', models.DateField()),
                ('repas_du', models.CharField(max_length=25)),
                ('repas_au', models.CharField(max_length=25)),
                ('mensa', models.CharField(max_length=25)),
                ('dit_messe', models.BooleanField(default=False)),
                ('messe_premier_jour', models.BooleanField(default=False)),
                ('tour_messe', models.CharField(max_length=25)),
                ('servant', models.BooleanField(default=False)),
                ('oratoire', models.CharField(max_length=50, null=True)),
                ('commentaire_cuisine', models.TextField()),
                ('commentaire_sacristie', models.TextField()),
                ('mail_sacristie', models.BooleanField(default=False)),
                ('mail_pere_suiveur', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotellerie.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Parloir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('repas', models.CharField(choices=[('Non défini', '---------'), ('Petit déjeuner', 'Petit déjeuner'), ('Déjeuner', 'Déjeuner'), ('Dîner', 'Dîner')], max_length=50)),
                ('nombre', models.IntegerField()),
                ('parloir', models.CharField(choices=[('Non défini', '---------'), ('Saint-Benoît', 'Saint-Benoît'), ('Saint-Ignace', 'Saint-Ignace'), ('Saint-Dominique', 'Saint-Dominique'), ('Parloir 1 vélux', 'Parloir 1 vélux'), ('Parloir 2 vélux', 'Parloir 2 vélux'), ('Salle de projection', 'Projection')], max_length=50)),
                ('repas_apporte', models.BooleanField(default=False)),
                ('remarque', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('personne_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parloir_personne_1', to='hotellerie.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_personne', to='hotellerie.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chambre', models.CharField(max_length=25)),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotellerie.sejour')),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.TextField()),
                ('code_postal', models.CharField(max_length=25)),
                ('ville', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_personne', to='hotellerie.personne')),
            ],
        ),
    ]
