# Generated by Django 3.2.18 on 2024-04-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotellerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parloir',
            name='personne_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parloir_personne_2', to='hotellerie.personne'),
        ),
        migrations.AddField(
            model_name='parloir',
            name='personne_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parloir_personne_3', to='hotellerie.personne'),
        ),
    ]
