# Generated by Django 3.2.18 on 2024-04-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellerie', '0002_auto_20240401_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parloir',
            name='nombre',
            field=models.IntegerField(null=True),
        ),
    ]
