# Generated by Django 3.2.18 on 2024-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellerie', '0003_alter_parloir_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sejour',
            name='commentaire_listing',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sejour',
            name='commentaire_cuisine',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sejour',
            name='commentaire_sacristie',
            field=models.TextField(null=True),
        ),
    ]
