# Generated by Django 4.2 on 2025-12-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellerie', '0004_auto_20240402_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personne',
            options={'ordering': ['nom', 'prenom', 'last_modified']},
        ),
        migrations.AddField(
            model_name='sejour',
            name='repas_detailles',
            field=models.CharField(default='', max_length=300),
        ),
    ]
