# Generated by Django 4.2 on 2025-12-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotellerie', '0005_alter_personne_options_sejour_repas_detailles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sejour',
            name='repas_detailles',
        ),
    ]
