# Generated by Django 4.2 on 2026-08-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellerie', '0006_remove_sejour_repas_detailles'),
    ]

    operations = [
        migrations.AddField(
            model_name='parloir',
            name='mange_refectoire',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='sejour',
        #     name='repas_detailles',
        #     field=models.CharField(default='', max_length=300),
        # ),
    ]
