# Generated by Django 3.2.18 on 2023-03-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=10)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('txt_hebrew', models.TextField(blank=True, null=True)),
                ('txt_greek', models.TextField(blank=True, null=True)),
                ('txt_latin', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
