# Generated by Django 3.2.18 on 2024-06-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='pen', max_length=255),
            preserve_default=False,
        ),
    ]
