# Generated by Django 3.2.18 on 2024-05-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=250)),
                ('cm', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=250)),
                ('page', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('ref', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=250)),
                ('page', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tierce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('antiphon', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=250)),
                ('rang', models.CharField(blank=True, max_length=25, null=True)),
                ('precedence', models.SmallIntegerField()),
                ('tierce', models.CharField(blank=True, max_length=250, null=True)),
                ('prayers_mg', models.CharField(blank=True, max_length=25, null=True)),
                ('proper_readings', models.BooleanField()),
                ('readings_cycle', models.SmallIntegerField(blank=True, null=True)),
                ('preface_name_latin', models.CharField(blank=True, max_length=255, null=True)),
                ('preface_name_french', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.CharField(blank=True, max_length=25, null=True)),
                ('preface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livrets.preface')),
            ],
        ),
    ]
