# Generated by Django 3.2.18 on 2024-06-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tierce',
        ),
        migrations.AlterField(
            model_name='score',
            name='page',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
