# Generated by Django 3.2.25 on 2025-03-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Toubib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=25)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('is_medecin', models.BooleanField()),
                ('adresse_1', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_2', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_3', models.CharField(blank=True, max_length=255, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infirmerie.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('when', models.DateTimeField()),
                ('where', models.CharField(max_length=25)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('facture', models.BooleanField(default=False)),
                ('gratis', models.BooleanField(default=False)),
                ('vitale', models.BooleanField(default=False)),
                ('remarque', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('toubib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets_toubib', to='infirmerie.toubib')),
            ],
        ),
    ]
