# Generated by Django 3.2.18 on 2023-12-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='agrafage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='encollage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='fixed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='gutters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='margins',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='massicot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='pelliculage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='rainage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='color',
            field=models.CharField(blank=True, choices=[('B&W', 'Noir'), ('CMYN', 'CMJN')], max_length=255, null=True),
        ),
    ]
