# Generated by Django 3.2.18 on 2023-12-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0002_auto_20231223_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
