# Generated by Django 3.2.18 on 2023-12-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0004_instructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructions',
            new_name='Work',
        ),
    ]
