# Generated by Django 3.2.18 on 2024-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0005_rename_instructions_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='dim1',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dim2',
            field=models.CharField(max_length=4),
        ),
    ]
