# Generated by Django 3.2.18 on 2024-01-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0006_auto_20240109_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
