# Generated by Django 3.2.18 on 2024-01-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0007_alter_element_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
