# Generated by Django 3.2.18 on 2024-01-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0008_alter_element_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='number_of_sheets_doc',
            new_name='number_of_pages_doc',
        ),
    ]
