# Generated by Django 3.2.18 on 2024-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0009_rename_number_of_sheets_doc_element_number_of_pages_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='fibers',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
