# Generated by Django 3.2.18 on 2024-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0010_element_fibers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='gutters',
            new_name='gutter_height',
        ),
        migrations.AddField(
            model_name='element',
            name='gutter_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
