# Generated by Django 3.2.18 on 2024-01-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0012_auto_20240110_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zip',
        ),
    ]
