# Generated by Django 3.2.18 on 2024-01-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0013_auto_20240110_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
