# Generated by Django 3.2.18 on 2024-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0015_element_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='thickness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
