# Generated by Django 4.2 on 2024-10-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0016_paper_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_home',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address_invoice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='various',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
