# Generated by Django 4.2 on 2024-11-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0017_client_address_home_client_address_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='price',
            new_name='price_remise',
        ),
    ]
