# Generated by Django 4.2 on 2024-11-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0018_rename_price_paper_price_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='price_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
