# Generated by Django 4.2 on 2025-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0021_client_email_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bl',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='invoice',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='quotation',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
