# Generated by Django 4.2 on 2025-02-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0022_project_bl_project_invoice_project_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='validated',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
