# Generated by Django 4.2 on 2025-07-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprimerie', '0023_remove_project_project_project_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='canceled',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
