# Generated by Django 3.2.18 on 2023-12-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(null=True)),
                ('go_date', models.DateField(null=True)),
                ('go_moment', models.CharField(max_length=25, null=True)),
                ('servants', models.BooleanField(null=True)),
                ('picnic', models.BooleanField(null=True)),
                ('go_by', models.CharField(max_length=25, null=True)),
                ('go_station', models.CharField(max_length=25, null=True)),
                ('go_hour', models.TimeField(null=True)),
                ('back_date', models.DateField()),
                ('back_moment', models.CharField(max_length=25, null=True)),
                ('keep_hot', models.BooleanField()),
                ('back_by', models.CharField(max_length=25, null=True)),
                ('back_station', models.CharField(max_length=25, null=True)),
                ('back_hour', models.TimeField(null=True)),
                ('ordinary_form', models.BooleanField(null=True)),
                ('commentary', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('additional_recipients', models.ManyToManyField(related_name='additional_recipients', to='moines.Monk')),
                ('monks', models.ManyToManyField(related_name='monks', to='moines.Monk')),
            ],
        ),
    ]
