# Generated by Django 3.2.18 on 2024-06-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(default='out', max_length=25),
            preserve_default=False,
        ),
    ]
